# Generated by Django 4.1.7 on 2023-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_amount', models.CharField(max_length=255)),
                ('expense_quantity', models.CharField(max_length=255)),
                ('qty_unit', models.CharField(max_length=255)),
                ('extra_note', models.TextField()),
                ('expense_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=255)),
                ('order_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('qty_weigth', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('date_of_delivery', models.CharField(max_length=255)),
                ('time_of_delivery', models.CharField(max_length=255)),
                ('extra_note', models.TextField()),
                ('order_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('pfp', models.ImageField(upload_to='s_pfps')),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
