# Generated by Django 4.1.7 on 2023-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0003_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(upload_to='users0_pfp'),
        ),
    ]
