# Generated by Django 4.1.7 on 2023-05-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0004_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill',
            field=models.ImageField(default=None, null=True, upload_to='users0_bill'),
        ),
    ]
