# Generated by Django 4.1.7 on 2023-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0005_expense_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_view',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
