# Generated by Django 4.1.7 on 2023-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0006_userprofile_first_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
