# Generated by Django 4.1.7 on 2023-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0007_userprofile_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
