# Generated by Django 4.1.7 on 2023-05-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0008_userprofile_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_end_date',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
