# Generated by Django 4.1.7 on 2023-05-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0009_userprofile_free_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
