# Generated by Django 4.1.7 on 2023-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0010_userprofile_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_selection',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
