# Generated by Django 4.1.7 on 2023-05-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0011_userprofile_theme_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_end_date',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_start_date',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
