# Generated by Django 4.1.7 on 2023-05-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0012_userprofile_premium_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_month_plan',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
