# Generated by Django 4.1.7 on 2023-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0013_userprofile_premium_month_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
