# Generated by Django 4.1.7 on 2023-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0014_userprofile_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='premium_month_plan',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
