# Generated by Django 4.1.7 on 2023-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0015_alter_userprofile_premium_month_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=10)),
                ('from_email', models.CharField(max_length=255)),
                ('issue', models.TextField()),
                ('date_time', models.CharField(max_length=255)),
            ],
        ),
    ]
