# Generated by Django 4.1.7 on 2023-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0016_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
