# Generated by Django 4.1.7 on 2023-06-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0017_tickets_solved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
        migrations.RenameModel(
            old_name='tickets',
            new_name='Ticket',
        ),
    ]
