# Generated by Django 4.2.1 on 2023-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_0', '0018_rename_sales_sale_rename_tickets_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
