# Generated by Django 4.2.1 on 2023-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_0", "0019_ticket_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="freemium",
            field=models.BooleanField(default=False),
        ),
    ]
