# Generated by Django 4.2.1 on 2023-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_0", "0020_userprofile_freemium"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemShopping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shopping_id", models.CharField(max_length=10)),
                ("item", models.CharField(max_length=255)),
                ("bought", models.BooleanField(default=False)),
                ("added", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
