# Generated by Django 4.2.1 on 2023-10-08 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user_0", "0022_tasklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=10)),
                ("item", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=10)),
                ("qty", models.CharField(max_length=10)),
                ("qty_unit", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=10)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
