# Generated by Django 4.1.7 on 2023-03-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('order_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('qty_weigth', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('date_of_delivery', models.CharField(max_length=255)),
                ('time_of_delivery', models.CharField(max_length=255)),
                ('extra_note', models.TextField()),
                ('order_date', models.CharField(max_length=255)),
            ],
        ),
    ]
