# Generated by Django 4.1.7 on 2023-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='user_id',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
