# Generated by Django 4.1.7 on 2023-03-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_sales_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_amount', models.CharField(max_length=255)),
                ('expense_quantity', models.CharField(max_length=255)),
                ('qty_unit', models.CharField(max_length=255)),
                ('extra_note', models.TextField()),
                ('expense_date', models.CharField(max_length=255)),
            ],
        ),
    ]
