# Generated by Django 4.1.7 on 2023-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='category',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
